Repository Arquisoft/wichat_en1b, pull requests merged in 2025-04, with the labels that each got.

#162 154 documentation for all the endpoints of the gatewayservice
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  questionservice/quest-service.js
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
  users/authservice/auth-service.js
  users/userservice/user-service.js
  webapp/src/components/Game/Question/Question.js
Labels: documentation, enhancement

#163 153 update readmemd file
  README.md
Labels: documentation

#169 168 create a nicer home page
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Home/Home.js
Labels: enhancement

#171 Fixed coverage for Back-end tests
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  questionservice/quest-service.js
  questionservice/quest-service.test.js
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-service.js
  users/userservice/user-service.test.js
Labels: enhancement

#176 Fixed lack of env_file on some services
  docker-compose.yml
Labels: bug

#172 Fixed Frontend tests
  package-lock.json
  package.json
  webapp/src/App.test.js
  webapp/src/components/Game/Chat/Chat.js
  webapp/src/components/Game/Chat/Chat.test.js
  webapp/src/components/Game/Question/Question.test.js
  webapp/src/components/Home/Home.test.js
  webapp/src/components/LogInSignUp/Login.test.js
  webapp/src/components/LogInSignUp/SignUp.test.js
Labels: bug

#181 Cache wikidata
  questionservice/controllers/WikidataController.js
  questionservice/controllers/questionTypes.js
  questionservice/models/question-model.js
  questionservice/models/wikidata-item-model.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/quest-model.js
  questionservice/quest-service.js
  questionservice/quest-service.test.js
  questionservice/repositories/QuestionRepository.js
  questionservice/repositories/WikidataItemRepository.js
Labels: bug, enhancement

#179 159 deploy the application
  .github/workflows/docker-push.yml
  docker-compose.yml
  webapp/Dockerfile
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/Question/Question.test.js
  webapp/src/components/Game/Question/StatisticsUpdater.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Statistics/RecordRetriever.js
Labels: enhancement

#188 Prototype actualization
  docs/resources/Presentación_prototipo_wichat.pdf
Labels: documentation

#185 Project documentation
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/05_building_block_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/13_annex.adoc
Labels: documentation

#207 👤 Feature: Adding profile pictures
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  statisticservice/statistics-service.test.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Profile/Profile.test.js
  webapp/src/components/Profile/UserProfileSettings.js
  webapp/src/components/Profile/components/ProfileHeader.jsx
  webapp/src/components/Statistics/Statistics.js
Labels: enhancement

#214 Strong password
  users/userservice/user-service.js
  users/userservice/user-service.test.js
Labels: enhancement

#217 Issue#203 repeat password
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/components/LogInSignUp/SignUp.js
  webapp/src/components/LogInSignUp/SignUp.test.js
  webapp/src/components/hooks/useAuth.js
Labels: enhancement

#223 193 leaderboard view
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Statistics/RecordRetriever.js
  webapp/src/components/Statistics/Statistics.js
  webapp/src/components/Statistics/Statistics.test.js
  webapp/src/components/Statistics/components/ErrorMessage.jsx
  webapp/src/components/Statistics/components/LoadingSpinner.jsx
  webapp/src/components/Statistics/components/StatisticsFilter.jsx
  webapp/src/components/Statistics/components/StatisticsTable.jsx
  webapp/src/components/Statistics/theme.css
Labels: enhancement

#237 229 improve statistics frontend
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
  webapp/src/components/Game/Question/Question.test.js
  webapp/src/components/Profile/components/ProfileHeader.jsx
  webapp/src/components/Statistics/RecordRetriever.js
  webapp/src/components/Statistics/Statistics.js
  webapp/src/components/Statistics/components/StatisticsFilter.jsx
  webapp/src/components/Statistics/components/StatisticsFilters.jsx
  webapp/src/components/Statistics/components/StatisticsTable.jsx
  webapp/src/components/Statistics/theme.css
Labels: enhancement

#218 Add gemini LLM + llm rotation
  README.md
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  llmservice/controllers/EmpathyController.js
  llmservice/controllers/GeminiController.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  llmservice/utils/system-prompt.js
  webapp/src/components/Home/Home.js
Labels: bug, enhancement

#234 App i18n
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  questionservice/controllers/WikidataController.js
  questionservice/controllers/questionTypes.js
  questionservice/models/question-model.js
  questionservice/quest-service.test.js
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/public/locales/ast.json
  webapp/public/locales/de.json
  webapp/public/locales/en.json
  webapp/public/locales/es.json
  webapp/public/locales/fr.json
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/Game/Chat/Chat.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/Question/StatisticsUpdater.js
  webapp/src/components/GameModes/GameModes.js
  webapp/src/components/Home/Home.js
  webapp/src/components/LogInSignUp/Login.js
  webapp/src/components/LogInSignUp/SignUp.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/Profile/UserProfileSettings.js
  webapp/src/components/Profile/components/AccountSettingsDialog.jsx
  webapp/src/components/Profile/components/AdditionalInsights.jsx
  webapp/src/components/Profile/components/AnswerDistribution.jsx
  webapp/src/components/Profile/components/ErrorState.jsx
  webapp/src/components/Profile/components/Insights.js
  webapp/src/components/Profile/components/ProfileHeader.jsx
  webapp/src/components/Profile/components/StatisticsSummary.jsx
  webapp/src/components/Profile/components/VisitorsSection.jsx
  webapp/src/components/Statistics/RecordRetriever.js
  webapp/src/components/Statistics/Statistics.js
  webapp/src/components/Statistics/components/StatisticsFilters.jsx
  webapp/src/components/Statistics/components/StatisticsTable.jsx
  webapp/src/components/fragments/Navbar.js
  webapp/src/i18n.js
  webapp/src/index.js
Labels: enhancement

#222 update wikidata SPARQL + add question of the day backend
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  questionservice/controllers/WikidataController.js
  questionservice/controllers/questionTypes.js
  questionservice/models/answer-model.js
  questionservice/models/question-day-model.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/quest-service.js
  questionservice/quest-service.test.js
  questionservice/repositories/AnswerRepository.js
  questionservice/repositories/QuestionOfTheDayRepository.js
Labels: bug, enhancement

#221 Implementation of e2e testing - Login and Register
  users/authservice/auth-model.js
  webapp/e2e/features/login-form.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/src/components/LogInSignUp/Login.js
  webapp/src/components/LogInSignUp/SignUp.js
  webapp/src/components/fragments/Navbar.js
  webapp/src/components/hooks/useAuth.js
Labels: enhancement

#246 240 question refactor
  webapp/public/locales/ast.json
  webapp/public/locales/de.json
  webapp/public/locales/en.json
  webapp/public/locales/es.json
  webapp/public/locales/fr.json
  webapp/src/components/Game/GameContext.js
  webapp/src/components/Game/GameWrapper.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/components/StatisticsUpdater.js
  webapp/src/components/GameModes/GameModes.js
  webapp/src/components/GameModes/gameModesConfiguration.js
  webapp/src/components/GameModes/strategies/custom.js
  webapp/src/components/GameModes/strategies/suddenDeath.js
  webapp/src/components/GameModes/strategyFactory.js
  webapp/src/components/hooks/useRounds.js
  webapp/src/components/hooks/useTimer.js
  webapp/src/components/utils/utils.js
Labels: enhancement
