Repository Arquisoft/wichat_en1b, pull requests merged in 2025-03, with the labels that each got.

#84 68 create database schema
  docs/images/databaseSchema.png
  docs/resources/DatabaseSchema.adoc
Labels: documentation, enhancement

#90 Updated build.yml and release.yml to add the question service microservice to the Github Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/quest-service.test.js
Labels: enhancement

#95 New stakeholders
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#104 Docker files Update
  docker-compose.yml
  questionservice/Dockerfile
Labels: enhancement

#107 Functional statistics service.
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
Labels: enhancement

#108 first wikidata fetching prototype
  questionservice/controllers/WikidataController.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/quest-service.js
Labels: enhancement

#102 First front-end components
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/CustomComponents.js
  webapp/src/components/CustomIcons.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Home/Home.test.js
  webapp/src/components/LogInSignUp/Login.js
  webapp/src/components/LogInSignUp/Login.test.js
  webapp/src/components/LogInSignUp/SignUp.js
  webapp/src/components/LogInSignUp/SignUp.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/fragments/Navbar.js
  webapp/src/components/fragments/Navbar.test.js
  webapp/src/components/hooks/useAuth.js
Labels: enhancement

#113 gateaway for question service
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  questionservice/quest-model.js
  questionservice/quest-service.js
Labels: enhancement

#122 fix deployment view diagrams
  docs/src/07_deployment_view.adoc
Labels: documentation

#128 First prototype
  docker-compose.yml
  gatewayservice/gateway-service.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  package-lock.json
  package.json
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/quest-service.js
  statisticservice/package-lock.json
  statisticservice/package.json
  statisticservice/statistics-model.js
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/authservice/package-lock.json
  users/authservice/package.json
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Home/Home.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/Profile/Profile.test.js
  webapp/src/components/Question/Question.js
  webapp/src/components/Question/Question.test.js
  webapp/src/components/Statistics/RecordRetriever.js
  webapp/src/components/Statistics/StatisticsPage.jsx
  webapp/src/components/fragments/Navbar.js
Labels: enhancement

#145 144 implementation of the llm chat
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Game/Chat/Chat.js
  webapp/src/components/Game/GameContext.js
  webapp/src/components/Game/GameWrapper.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/Question/Question.test.js
Labels: enhancement

#148 134 start the llm integration work backend
  docker-compose.yml
  gatewayservice/gateway-service.js
  gatewayservice/package-lock.json
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  llmservice/package-lock.json
  llmservice/package.json
  webapp/src/components/Game/Chat/Chat.js
Labels: enhancement

#147 Enhancement of tests in gateway service and
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
Labels: enhancement
