Repository Arquisoft/wichat_en1b, pull requests merged in 2025-02, with the labels that each got.

#2 Fix issue update readme
  README.md
Labels: documentation

#5 LLM_Comparison.adoc file moved to a new directory.
  docs/resources/LLM_Comparison.adoc
Labels: documentation

#6 Deleted file package-lock.json from /users directory (issue #3)
  users/package-lock.json
Labels: bug, invalid

#13 Issue#9 Add context to Documentation
  docs/src/03_context_and_scope.adoc
Labels: documentation

#14 Issue#8 Add stakeholders to Documentation
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#18 Doc Introduction and goals
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#19 Add documentation for the project constraints
  docs/src/02_architecture_constraints.adoc
Labels: documentation

#21 Fixed bug from issue #20
  docs/src/02_architecture_constraints.adoc
Labels: bug, documentation

#22 add technologies to documentation
  docs/src/04_solution_strategy.adoc
Labels: documentation

#37 Issue#30 quality requirements
  docs/src/10_quality_requirements.adoc
Labels: documentation

#39 31 write documentation for the risks and technical debts
  docs/src/11_technical_risks.adoc
Labels: documentation

#40 Issue#32-write-documentation-for-the-annex
  docs/index.adoc
  docs/src/13_annex.adoc
Labels: documentation

#41 Issue#25 Write documentation for the building block view
  docs/images/05_building_blocks-EN_1.png
  docs/images/05_building_blocks-EN_2.png
  docs/images/05_building_blocks-EN_3.png
  docs/src/05_building_block_view.adoc
Labels: documentation

#43 Issue#34 Write documentation for the glossary elements
  docs/src/12_glossary.adoc
Labels: documentation

#44 Add documentation for deployment information & deployment view
  docs/src/07_deployment_view.adoc
Labels: documentation

#46 fix solution strategy documentation
  docs/src/04_solution_strategy.adoc
Labels: documentation

#48 Wrote documentation for the runtime view part
  docs/src/06_runtime_view.adoc
Labels: documentation

#53 Fixed bug and improve uml
  docs/src/06_runtime_view.adoc
Labels: bug, documentation

#70 Issue#59-fix-api-key-exposure
  .github/workflows/release.yml
  .vscode/settings.json
  README.md
  docker-compose.yml
  llmservice/.dockerignore
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  llmservice/package-lock.json
  llmservice/package.json
  webapp/Dockerfile
  webapp/src/App.js
  webapp/src/components/Login.js
Labels: bug

#73 Issues 58, 60 and 61.
  docs/src/01_introduction_and_goals.adoc
  docs/src/13_annex.adoc
Labels: documentation

#72 56 fix runtime view
  docs/src/06_runtime_view.adoc
Labels: documentation

#79 Question service created, listens in port 8004
  questionservice/.dockerignore
  questionservice/Dockerfile
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/quest-service.js
  questionservice/quest-service.test.js
Labels: enhancement

#74 55 fix technical constraints
  docs/src/02_architecture_constraints.adoc
Labels: bug, documentation

#81 Fixed bug in LLM Chat Interaction Flow diagram introduced in pr #72
  docs/src/06_runtime_view.adoc
Labels: bug, documentation

#82 Fixed architecture decisions in documentation
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#83 fix context & scope diagram documentation
  docs/src/03_context_and_scope.adoc
Labels: documentation
