Repository Arquisoft/wichat_en1b, pull requests merged in 2025-05, with the labels that each got.

#248 Question of the day + improvements
  gatewayservice/openapi.yaml
  questionservice/controllers/WikidataController.js
  questionservice/models/answer-model.js
  questionservice/quest-service.js
  questionservice/repositories/AnswerRepository.js
  questionservice/repositories/QuestionRepository.js
  webapp/public/locales/ast.json
  webapp/public/locales/de.json
  webapp/public/locales/en.json
  webapp/public/locales/es.json
  webapp/public/locales/fr.json
  webapp/src/App.js
  webapp/src/components/Game/Chat/Chat.js
  webapp/src/components/Game/Question/GameEndScreen.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/components/StatisticsUpdater.js
  webapp/src/components/hooks/useAuth.js
  webapp/src/components/layouts/ProtectedLayout.js
Labels: bug, enhancement

#245 Implementation of E2E for Profile interaction
  README.md
  webapp/e2e/features/profile-statistics.feature
  webapp/e2e/jest.config.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/profile-statistics.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
  webapp/package.json
Labels: enhancement

#253 Fixed bug. Chat now clears the messages at the end of the round
  statisticservice/statistics-service.js
  webapp/public/locales/ast.json
  webapp/public/locales/de.json
  webapp/public/locales/en.json
  webapp/public/locales/es.json
  webapp/public/locales/fr.json
  webapp/src/components/Game/Chat/Chat.js
  webapp/src/components/Game/GameContext.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/Profile/components/AdditionalInsights.jsx
  webapp/src/components/Profile/components/Insights.js
  webapp/src/components/fragments/Navbar.js
Labels: bug, enhancement

#239 238 fix frontend tests
  llmservice/controllers/EmpathyController.js
  llmservice/controllers/EmpathyController.test.js
  llmservice/controllers/GeminiController.js
  llmservice/controllers/GeminiController.test.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  users/userservice/user-service.test.js
  webapp/Dockerfile
  webapp/public/locales/ast.json
  webapp/public/locales/de.json
  webapp/public/locales/en.json
  webapp/public/locales/es.json
  webapp/public/locales/fr.json
  webapp/src/App.test.js
  webapp/src/components/Game/Chat/Chat.test.js
  webapp/src/components/Game/GameContext.js
  webapp/src/components/Game/GameContext.test.js
  webapp/src/components/Game/GameWrapper.test.js
  webapp/src/components/Game/Question/GameEndScreen.js
  webapp/src/components/Game/Question/GameEndScreen.test.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/Question/Question.test.js
  webapp/src/components/Game/components/StatisticsUpdater.test.js
  webapp/src/components/GameModes/GameModes.js
  webapp/src/components/GameModes/GameModes.test.js
  webapp/src/components/GameModes/gameModesConfiguration.test.js
  webapp/src/components/GameModes/strategies/custom.test.js
  webapp/src/components/GameModes/strategies/suddenDeath.test.js
  webapp/src/components/Home/Home.test.js
  webapp/src/components/Profile/Profile.js
  webapp/src/components/Profile/Profile.test.js
  webapp/src/components/Profile/RecordRetrieverProfile.js
  webapp/src/components/Profile/UserProfileSettings.test.js
  webapp/src/components/Profile/components/AccountSettingsDialog.jsx
  webapp/src/components/Profile/components/AccountSettingsDialog.test.js
  webapp/src/components/Profile/components/AdditionalInsights.jsx
  webapp/src/components/Profile/components/Insights.js
  webapp/src/components/Profile/components/Insights.test.js
  webapp/src/components/Profile/components/ProfileHeader.jsx
  webapp/src/components/Profile/components/ProfileHeader.test.js
  webapp/src/components/Profile/components/StatisticsSummary.test.js
  webapp/src/components/Profile/components/VisitorsSection.jsx
  webapp/src/components/Statistics/RecordRetriever.test.js
  webapp/src/components/Statistics/Statistics.js
  webapp/src/components/Statistics/Statistics.test.js
  webapp/src/components/Statistics/components/StatisticsFilters.test.js
  webapp/src/components/Statistics/components/StatisticsTable.test.js
  webapp/src/components/fragments/Navbar.test.js
  webapp/src/components/hooks/useAuth.js
  webapp/src/components/hooks/useRounds.js
  webapp/src/components/hooks/useTimer.test.js
  webapp/src/components/layouts/ProtectedLayout.test.js
  webapp/src/setupTests.js
Labels: bug

#258 Update Database Schema
  docs/images/databaseSchema.png
  docs/resources/DatabaseSchema.md
  users/authservice/auth-model.js
  users/userservice/user-model.js
Labels: documentation

#257 Gatling - load testing java project
  .dockerignore
  README.md
  load-testing/.gatling/example.package.conf
  load-testing/.gatling/package.conf
  load-testing/.gitignore
  load-testing/.mvn/wrapper/maven-wrapper.properties
  load-testing/README.md
  load-testing/mvnw
  load-testing/mvnw.cmd
  load-testing/pom.xml
  load-testing/src/test/java/io/gatling/demo/CustomGameSimulation.java
  load-testing/src/test/java/io/gatling/demo/LoginSimulation.java
  load-testing/src/test/java/io/gatling/demo/QODSimulation.java
  load-testing/src/test/java/io/gatling/demo/UploadProfileImgSimulation.java
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0006_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0012_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0013_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0014_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0015_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0016_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0017_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0018_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0019_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0020_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0021_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0022_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0023_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0024_request.dat
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0026_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0034_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0038_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0041_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0043_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0047_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0049_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0052_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0055_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0058_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0061_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0064_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0067_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0069_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0072_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0075_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0078_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0081_request.json
  load-testing/src/test/java/io/gatling/demo/customgamesimulation/0083_request.json
  load-testing/src/test/java/io/gatling/demo/loginsimulation/0006_request.json
  load-testing/src/test/java/io/gatling/demo/loginsimulation/0013_request.json
  load-testing/src/test/java/io/gatling/demo/loginsimulation/0020_request.json
  load-testing/src/test/java/io/gatling/demo/uploadprofileimgsimulation/0025_request.json
  load-testing/src/test/resources/gatling.conf
  load-testing/src/test/resources/logback-test.xml
Labels: enhancement

#250 E2E gameplay-testing
  webapp/e2e/features/gameplay.feature
  webapp/e2e/mocks/insertMockQuestions.js
  webapp/e2e/mocks/mockQuestions.js
  webapp/e2e/steps/gameplay.steps.js
Labels: enhancement

#262 Merge adjust image sizes
  webapp/src/components/Game/Question/Question.js
Labels: bug

#263 Added buttons to redirect to home and game modes in the end screen of…
  webapp/public/locales/ast.json
  webapp/public/locales/de.json
  webapp/public/locales/en.json
  webapp/public/locales/es.json
  webapp/public/locales/fr.json
  webapp/src/components/Game/Question/GameEndScreen.js
  webapp/src/components/Game/Question/GameEndScreen.test.js
Labels: enhancement

#270 Updated and created new enpoint documentation.
  gatewayservice/openapi.yaml
Labels: documentation

#274 Changed filter logic in MongoDB pipeline to fix global stats.
  statisticservice/statistics-service.js
  statisticservice/statistics-service.test.js
Labels: bug

#276 fix time up functionality
  webapp/src/components/Game/GameContext.js
  webapp/src/components/Game/Question/Question.js
  webapp/src/components/Game/Question/Question.test.js
  webapp/src/components/hooks/useRounds.js
  webapp/src/components/hooks/useTimer.js
  webapp/src/components/hooks/useTimer.test.js
Labels: bug
